apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-fjtfd
    field.cattle.io/ingressState: '{"aGVsbG8td29ybGQvaGVsbG8td29ybGQveGlwLmlvLy84MA==":"deployment:hello-world:hello-world"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["172.22.101.111"],"port":80,"protocol":"HTTP","serviceName":"hello-world:ingress-6accc3f64f831ecf197448c0001fe50f","ingressName":"hello-world:hello-world","hostname":"hello-world.hello-world.172.22.101.111.xip.io","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
  name: hello-world
  selfLink: /apis/extensions/v1beta1/namespaces/hello-world/ingresses/hello-world
spec:
  rules:
  - host: hello-world.hello-world.172.22.101.111.xip.io
    http:
      paths:
      - backend:
          serviceName: ingress-6accc3f64f831ecf197448c0001fe50f
          servicePort: 80
status:
  loadBalancer: {}
