apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-mmjg2
    field.cattle.io/ingressState: '{"aGVsbG8td29ybGQtaW5ncmVzcy9sZXZlbnQveGlwLmlvLy84MA==":"deployment:levent:hello-world"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["172.22.101.111"],"port":80,"protocol":"HTTP","serviceName":"levent:ingress-85ec007e04a4bbdb3dd347907b6c7b96","ingressName":"levent:hello-world-ingress","hostname":"hello-world-ingress.levent.172.22.101.111.xip.io","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
  name: hello-world-ingress
  selfLink: /apis/extensions/v1beta1/namespaces/levent/ingresses/hello-world-ingress
spec:
  rules:
  - host: hello-world-ingress.levent.172.22.101.111.xip.io
    http:
      paths:
      - backend:
          serviceName: ingress-85ec007e04a4bbdb3dd347907b6c7b96
          servicePort: 80
status:
  loadBalancer: {}
